<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Seeder de libros para la biblioteca digital
 * 
 * Crea 25 libros de prueba con datos realistas incluyendo:
 * - Información básica (título, ISBN, páginas, año)
 * - Relaciones (categorías, autores, editorial)
 * - Estadísticas simuladas (descargas, vistas, préstamos)
 * - Variedad de tipos (digital, físico, ambos)
 * 
 * Los datos incluyen literatura peruana, clásicos universales,
 * libros técnicos y académicos para demostrar todas las funcionalidades.
 * 
 * @package Database\Seeders
 */
class BookSeeder extends Seeder
{
    /**
     * Ejecutar el seeder
     * 
     * Proceso:
     * 1. Crear 25 libros en la tabla books
     * 2. Asignar categorías a cada libro (tabla pivot book_category)
     * 3. Crear detalles extendidos (tabla book_details)
     * 4. Crear contribuidores/autores (tabla book_contributors)
     * 
     * @return void
     */
    public function run(): void
    {
        // Array con 25 libros de prueba
        $books = [
            [
                'title' => 'Cien Años de Soledad',
                'publisher_id' => 3, // Editorial Planeta
                'isbn' => '9788497592208',
                'language_code' => 'es',
                'pages' => 471,
                'publication_year' => 1967,
                'cover_image' => null, // Se puede agregar portada en storage/app/public/covers/
                'pdf_file' => null,    // Se puede agregar PDF en storage/app/public/books/
                'is_active' => true,
                'downloadable' => true,
                'book_type' => 'both', // Disponible digital y físico
                'total_downloads' => 150,
                'total_physical_copies' => 3,
                'available_physical_copies' => 2,
                'total_loans' => 45,
                'total_views' => 580,
                'featured' => true,
                'access_level' => 'free',
                'copyright_status' => 'copyrighted',
                'published_at' => now(),
            ],
            [
                'title' => 'El Mundo es Ancho y Ajeno',
                'publisher_id' => 1, // San Marcos
                'isbn' => '9786124597329',
                'language_code' => 'es',
                'pages' => 608,
                'publication_year' => 1941,
                'cover_image' => null,
                'pdf_file' => null,
                'is_active' => true,
                'downloadable' => true,
                'book_type' => 'both',
                'total_downloads' => 89,
                'total_physical_copies' => 5,
                'available_physical_copies' => 3,
                'total_loans' => 67,
                'total_views' => 320,
                'featured' => true,
                'access_level' => 'free',
                'copyright_status' => 'public_domain',
                'published_at' => now(),
            ],
            [
                'title' => 'La Ciudad y los Perros',
                'publisher_id' => 4, // Alfaguara
                'isbn' => '9788420482248',
                'language_code' => 'es',
                'pages' => 408,
                'publication_year' => 1963,
                'cover_image' => null,
                'pdf_file' => null,
                'is_active' => true,
                'downloadable' => true,
                'book_type' => 'both',
                'total_downloads' => 234,
                'total_physical_copies' => 4,
                'available_physical_copies' => 1,
                'total_loans' => 123,
                'total_views' => 890,
                'featured' => true,
                'access_level' => 'free',
                'copyright_status' => 'copyrighted',
                'published_at' => now(),
            ],
            [
                'title' => 'Historia del Perú Contemporáneo',
                'publisher_id' => 2, // PUCP
                'isbn' => '9786124146724',
                'language_code' => 'es',
                'pages' => 512,
                'publication_year' => 2020,
                'cover_image' => null,
                'pdf_file' => null,
                'is_active' => true,
                'downloadable' => true,
                'book_type' => 'digital',
                'total_downloads' => 67,
                'total_physical_copies' => 0,
                'available_physical_copies' => 0,
                'total_loans' => 0,
                'total_views' => 145,
                'featured' => false,
                'access_level' => 'institutional',
                'copyright_status' => 'copyrighted',
                'published_at' => now(),
            ],
            [
                'title' => 'Introducción a la Programación con Python',
                'publisher_id' => 2, // PUCP
                'isbn' => '9786123456789',
                'language_code' => 'es',
                'pages' => 356,
                'publication_year' => 2023,
                'cover_image' => null,
                'pdf_file' => null,
                'is_active' => true,
                'downloadable' => true,
                'book_type' => 'digital',
                'total_downloads' => 342,
                'total_physical_copies' => 0,
                'available_physical_copies' => 0,
                'total_loans' => 0,
                'total_views' => 1205,
                'featured' => true,
                'access_level' => 'free',
                'copyright_status' => 'creative_commons',
                'license_type' => 'CC BY-NC-SA 4.0',
                'published_at' => now(),
            ],
            [
                'title' => 'Constitución Política del Perú Comentada',
                'publisher_id' => 1, // San Marcos
                'isbn' => '9786124597456',
                'language_code' => 'es',
                'pages' => 892,
                'publication_year' => 2022,
                'cover_image' => null,
                'pdf_file' => null,
                'is_active' => true,
                'downloadable' => true,
                'book_type' => 'both',
                'total_downloads' => 456,
                'total_physical_copies' => 8,
                'available_physical_copies' => 5,
                'total_loans' => 234,
                'total_views' => 1890,
                'featured' => true,
                'access_level' => 'free',
                'copyright_status' => 'copyrighted',
                'published_at' => now(),
            ],
            [
                'title' => 'Anatomía Humana Descriptiva',
                'publisher_id' => 2, // PUCP
                'isbn' => '9786123987654',
                'language_code' => 'es',
                'pages' => 1024,
                'publication_year' => 2021,
                'cover_image' => null,
                'pdf_file' => null,
                'is_active' => true,
                'downloadable' => true,
                'book_type' => 'both',
                'total_downloads' => 178,
                'total_physical_copies' => 6,
                'available_physical_copies' => 4,
                'total_loans' => 89,
                'total_views' => 567,
                'featured' => false,
                'access_level' => 'institutional',
                'copyright_status' => 'copyrighted',
                'published_at' => now(),
            ],
            [
                'title' => 'Microeconomía Avanzada',
                'publisher_id' => 2, // PUCP
                'isbn' => '9786124598765',
                'language_code' => 'es',
                'pages' => 678,
                'publication_year' => 2022,
                'cover_image' => null,
                'pdf_file' => null,
                'is_active' => true,
                'downloadable' => true,
                'book_type' => 'digital',
                'total_downloads' => 234,
                'total_physical_copies' => 0,
                'available_physical_copies' => 0,
                'total_loans' => 0,
                'total_views' => 789,
                'featured' => false,
                'access_level' => 'premium',
                'copyright_status' => 'copyrighted',
                'published_at' => now(),
            ],
            [
                'title' => 'Pedagogía del Oprimido',
                'publisher_id' => 1, // San Marcos
                'isbn' => '9789682315985',
                'language_code' => 'es',
                'pages' => 246,
                'publication_year' => 1970,
                'cover_image' => null,
                'pdf_file' => null,
                'is_active' => true,
                'downloadable' => true,
                'book_type' => 'both',
                'total_downloads' => 567,
                'total_physical_copies' => 10,
                'available_physical_copies' => 7,
                'total_loans' => 345,
                'total_views' => 2134,
                'featured' => true,
                'access_level' => 'free',
                'copyright_status' => 'public_domain',
                'published_at' => now(),
            ],
            [
                'title' => 'Física Cuántica para Ingenieros',
                'publisher_id' => 2, // PUCP
                'isbn' => '9786123654789',
                'language_code' => 'es',
                'pages' => 534,
                'publication_year' => 2023,
                'cover_image' => null,
                'pdf_file' => null,
                'is_active' => true,
                'downloadable' => true,
                'book_type' => 'digital',
                'total_downloads' => 98,
                'total_physical_copies' => 0,
                'available_physical_copies' => 0,
                'total_loans' => 0,
                'total_views' => 234,
                'featured' => false,
                'access_level' => 'institutional',
                'copyright_status' => 'copyrighted',
                'published_at' => now(),
            ],
            // ===== LIBROS ADICIONALES PARA PAGINACIÓN =====
            [
                'title' => 'Don Quijote de la Mancha',
                'publisher_id' => 3,
                'isbn' => '9788491050407',
                'language_code' => 'es',
                'pages' => 1200,
                'publication_year' => 2015, // Edición moderna
                'cover_image' => null,
                'pdf_file' => null,
                'is_active' => true,
                'downloadable' => true,
                'book_type' => 'both',
                'total_downloads' => 320,
                'total_physical_copies' => 5,
                'available_physical_copies' => 4,
                'total_loans' => 89,
                'total_views' => 1200,
                'featured' => true,
                'access_level' => 'free',
                'copyright_status' => 'public_domain',
                'published_at' => now(),
            ],
            [
                'title' => 'Rayuela',
                'publisher_id' => 4,
                'isbn' => '9788420482231',
                'language_code' => 'es',
                'pages' => 736,
                'publication_year' => 1963,
                'cover_image' => null,
                'pdf_file' => null,
                'is_active' => true,
                'downloadable' => true,
                'book_type' => 'digital',
                'total_downloads' => 189,
                'total_physical_copies' => 0,
                'available_physical_copies' => 0,
                'total_loans' => 0,
                'total_views' => 678,
                'featured' => true,
                'access_level' => 'free',
                'copyright_status' => 'copyrighted',
                'published_at' => now(),
            ],
            [
                'title' => 'El Señor de los Anillos: La Comunidad del Anillo',
                'publisher_id' => 3,
                'isbn' => '9788445077528',
                'language_code' => 'es',
                'pages' => 576,
                'publication_year' => 1954,
                'cover_image' => null,
                'pdf_file' => null,
                'is_active' => true,
                'downloadable' => false,
                'book_type' => 'physical',
                'total_downloads' => 0,
                'total_physical_copies' => 3,
                'available_physical_copies' => 1,
                'total_loans' => 145,
                'total_views' => 890,
                'featured' => true,
                'access_level' => 'free', // Cambiadoa free
                'copyright_status' => 'copyrighted',
                'published_at' => now(),
            ],
            [
                'title' => 'Introducción al Machine Learning',
                'publisher_id' => 1,
                'isbn' => '9786124000001',
                'language_code' => 'es',
                'pages' => 450,
                'publication_year' => 2022,
                'cover_image' => null,
                'pdf_file' => null,
                'is_active' => true,
                'downloadable' => true,
                'book_type' => 'digital',
                'total_downloads' => 567,
                'total_physical_copies' => 0,
                'available_physical_copies' => 0,
                'total_loans' => 0,
                'total_views' => 1340,
                'featured' => false,
                'access_level' => 'premium',
                'copyright_status' => 'copyrighted',
                'published_at' => now(),
            ],
            [
                'title' => 'Bases de Datos Relacionales',
                'publisher_id' => 1,
                'isbn' => '9786124000002',
                'language_code' => 'es',
                'pages' => 380,
                'publication_year' => 2021,
                'cover_image' => null,
                'pdf_file' => null,
                'is_active' => true,
                'downloadable' => true,
                'book_type' => 'digital',
                'total_downloads' => 234,
                'total_physical_copies' => 0,
                'available_physical_copies' => 0,
                'total_loans' => 0,
                'total_views' => 456,
                'featured' => false,
                'access_level' => 'free',
                'copyright_status' => 'creative_commons',
                'published_at' => now(),
            ],
            [
                'title' => 'Química Orgánica',
                'publisher_id' => 2,
                'isbn' => '9786123999888',
                'language_code' => 'es',
                'pages' => 890,
                'publication_year' => 2019,
                'cover_image' => null,
                'pdf_file' => null,
                'is_active' => true,
                'downloadable' => true,
                'book_type' => 'both',
                'total_downloads' => 123,
                'total_physical_copies' => 4,
                'available_physical_copies' => 3,
                'total_loans' => 34,
                'total_views' => 267,
                'featured' => false,
                'access_level' => 'institutional',
                'copyright_status' => 'copyrighted',
                'published_at' => now(),
            ],
            [
                'title' => 'Historia del Arte Universal',
                'publisher_id' => 3,
                'isbn' => '9788445098765',
                'language_code' => 'es',
                'pages' => 1024,
                'publication_year' => 2018,
                'cover_image' => null,
                'pdf_file' => null,
                'is_active' => true,
                'downloadable' => true,
                'book_type' => 'both',
                'total_downloads' => 345,
                'total_physical_copies' => 2,
                'available_physical_copies' => 2,
                'total_loans' => 12,
                'total_views' => 789,
                'featured' => false,
                'access_level' => 'free',
                'copyright_status' => 'copyrighted',
                'published_at' => now(),
            ],
            [
                'title' => 'Cálculo Diferencial e Integral',
                'publisher_id' => 1,
                'isbn' => '9786124567890',
                'language_code' => 'es',
                'pages' => 567,
                'publication_year' => 2020,
                'cover_image' => null,
                'pdf_file' => null,
                'is_active' => true,
                'downloadable' => true,
                'book_type' => 'digital',
                'total_downloads' => 678,
                'total_physical_copies' => 0,
                'available_physical_copies' => 0,
                'total_loans' => 0,
                'total_views' => 1123,
                'featured' => false,
                'access_level' => 'free',
                'copyright_status' => 'creative_commons',
                'published_at' => now(),
            ],
            [
                'title' => 'Psicología del Desarrollo',
                'publisher_id' => 2,
                'isbn' => '9786125678901',
                'language_code' => 'es',
                'pages' => 423,
                'publication_year' => 2021,
                'cover_image' => null,
                'pdf_file' => null,
                'is_active' => true,
                'downloadable' => true,
                'book_type' => 'both',
                'total_downloads' => 198,
                'total_physical_copies' => 3,
                'available_physical_copies' => 3,
                'total_loans' => 23,
                'total_views' => 456,
                'featured' => false,
                'access_level' => 'free',
                'copyright_status' => 'copyrighted',
                'published_at' => now(),
            ],
            [
                'title' => 'Filosofía Contemporánea',
                'publisher_id' => 4,
                'isbn' => '9788420123456',
                'language_code' => 'es',
                'pages' => 512,
                'publication_year' => 2019,
                'cover_image' => null,
                'pdf_file' => null,
                'is_active' => true,
                'downloadable' => true,
                'book_type' => 'digital',
                'total_downloads' => 234,
                'total_physical_copies' => 0,
                'available_physical_copies' => 0,
                'total_loans' => 0,
                'total_views' => 567,
                'featured' => false,
                'access_level' => 'free',
                'copyright_status' => 'copyrighted',
                'published_at' => now(),
            ],
            [
                'title' => 'Álgebra Lineal',
                'publisher_id' => 1,
                'isbn' => '9786126789012',
                'language_code' => 'es',
                'pages' => 389,
                'publication_year' => 2022,
                'cover_image' => null,
                'pdf_file' => null,
                'is_active' => true,
                'downloadable' => true,
                'book_type' => 'digital',
                'total_downloads' => 456,
                'total_physical_copies' => 0,
                'available_physical_copies' => 0,
                'total_loans' => 0,
                'total_views' => 890,
                'featured' => false,
                'access_level' => 'free',
                'copyright_status' => 'creative_commons',
                'published_at' => now(),
            ],
            [
                'title' => 'Biología Molecular',
                'publisher_id' => 2,
                'isbn' => '9786127890123',
                'language_code' => 'es',
                'pages' => 678,
                'publication_year' => 2020,
                'cover_image' => null,
                'pdf_file' => null,
                'is_active' => false, // Inactivo para probar filtros
                'downloadable' => true,
                'book_type' => 'both',
                'total_downloads' => 123,
                'total_physical_copies' => 2,
                'available_physical_copies' => 2,
                'total_loans' => 8,
                'total_views' => 234,
                'featured' => false,
                'access_level' => 'institutional',
                'copyright_status' => 'copyrighted',
                'published_at' => now(),
            ],
            [
                'title' => 'Derecho Procesal Civil',
                'publisher_id' => 2,
                'isbn' => '9786128901234',
                'language_code' => 'es',
                'pages' => 756,
                'publication_year' => 2021,
                'cover_image' => null,
                'pdf_file' => null,
                'is_active' => true,
                'downloadable' => true,
                'book_type' => 'both',
                'total_downloads' => 187,
                'total_physical_copies' => 4,
                'available_physical_copies' => 3,
                'total_loans' => 45,
                'total_views' => 456,
                'featured' => false,
                'access_level' => 'free',
                'copyright_status' => 'copyrighted',
                'published_at' => now(),
            ],
            [
                'title' => 'Estadística Aplicada',
                'publisher_id' => 1,
                'isbn' => '9786129012345',
                'language_code' => 'es',
                'pages' => 445,
                'publication_year' => 2023,
                'cover_image' => null,
                'pdf_file' => null,
                'is_active' => true,
                'downloadable' => true,
                'book_type' => 'digital',
                'total_downloads' => 589,
                'total_physical_copies' => 0,
                'available_physical_copies' => 0,
                'total_loans' => 0,
                'total_views' => 1234,
                'featured' => true,
                'access_level' => 'free',
                'copyright_status' => 'creative_commons',
                'published_at' => now(),
            ],
            [
                'title' => 'Marketing Digital',
                'publisher_id' => 3,
                'isbn' => '9788445123456',
                'language_code' => 'es',
                'pages' => 356,
                'publication_year' => 2023,
                'cover_image' => null,
                'pdf_file' => null,
                'is_active' => true,
                'downloadable' => true,
                'book_type' => 'digital',
                'total_downloads' => 789,
                'total_physical_copies' => 0,
                'available_physical_copies' => 0,
                'total_loans' => 0,
                'total_views' => 1567,
                'featured' => true,
                'access_level' => 'premium',
                'copyright_status' => 'copyrighted',
                'published_at' => now(),
            ],
        ];

        foreach ($books as $book) {
            $bookId = DB::table('books')->insertGetId([
                ...$book,
                'created_at' => now(),
                'updated_at' => now(),
            ]);

            // Asignar categorías a cada libro
            $this->assignCategories($bookId, $book['title']);

            // Crear detalles del libro
            $this->createBookDetails($bookId, $book);

            // Crear contribuidores (autores)
            $this->createContributors($bookId, $book['title']);
        }
    }

    private function assignCategories($bookId, $title)
    {
        $categoryMap = [
            'Cien Años de Soledad' => ['literatura'],
            'El Mundo es Ancho y Ajeno' => ['literatura', 'novela-peruana'],
            'La Ciudad y los Perros' => ['literatura', 'novela-peruana'],
            'Historia del Perú Contemporáneo' => ['historia'],
            'Introducción a la Programación con Python' => ['tecnologia'],
            'Constitución Política del Perú Comentada' => ['derecho'],
            'Anatomía Humana Descriptiva' => ['medicina'],
            'Microeconomía Avanzada' => ['economia'],
            'Pedagogía del Oprimido' => ['educacion'],
            'Física Cuántica para Ingenieros' => ['ciencias'],
            'Don Quijote de la Mancha' => ['literatura'],
            'Rayuela' => ['literatura'],
            'El Señor de los Anillos: La Comunidad del Anillo' => ['literatura'],
            'Introducción al Machine Learning' => ['tecnologia'],
            'Bases de Datos Relacionales' => ['tecnologia'],
            'Química Orgánica' => ['ciencias'],
            'Historia del Arte Universal' => ['historia'],
            'Cálculo Diferencial e Integral' => ['ciencias'],
            'Psicología del Desarrollo' => ['medicina'],
            'Filosofía Contemporánea' => ['literatura'],
            'Álgebra Lineal' => ['ciencias'],
            'Biología Molecular' => ['medicina'],
            'Derecho Procesal Civil' => ['derecho'],
            'Estadística Aplicada' => ['ciencias'],
            'Marketing Digital' => ['economia'],
        ];

        $slugs = $categoryMap[$title] ?? ['literatura'];

        foreach ($slugs as $slug) {
            $categoryId = DB::table('categories')->where('slug', $slug)->value('id');
            if ($categoryId) {
                DB::table('book_category')->insert([
                    'book_id' => $bookId,
                    'category_id' => $categoryId,
                    'created_at' => now(),
                    'updated_at' => now(),
                ]);
            }
        }
    }

    private function createBookDetails($bookId, $book)
    {
        $descriptions = [
            'Cien Años de Soledad' => 'Obra maestra del realismo mágico que narra la historia de la familia Buendía a lo largo de varias generaciones en el pueblo ficticio de Macondo.',
            'El Mundo es Ancho y Ajeno' => 'Novela indigenista que retrata la lucha de las comunidades indígenas peruanas por defender sus tierras.',
            'La Ciudad y los Perros' => 'Primera novela de Mario Vargas Llosa que narra la vida de un grupo de cadetes en el Colegio Militar Leoncio Prado.',
            'Historia del Perú Contemporáneo' => 'Análisis exhaustivo de la historia peruana desde la independencia hasta nuestros días.',
            'Introducción a la Programación con Python' => 'Guía completa para aprender programación desde cero utilizando el lenguaje Python.',
            'Constitución Política del Perú Comentada' => 'Análisis artículo por artículo de la Constitución Política del Perú de 1993.',
            'Anatomía Humana Descriptiva' => 'Texto completo de anatomía humana con ilustraciones detalladas.',
            'Microeconomía Avanzada' => 'Teoría microeconómica avanzada con aplicaciones prácticas.',
            'Pedagogía del Oprimido' => 'Obra fundamental de Paulo Freire sobre educación liberadora.',
            'Física Cuántica para Ingenieros' => 'Introducción a la mecánica cuántica aplicada a la ingeniería.',
            'Don Quijote de la Mancha' => 'Clásico de la literatura universal que narra las aventuras de Alonso Quijano.',
            'Rayuela' => 'Novela experimental de Julio Cortázar que propone múltiples lecturas.',
            'El Señor de los Anillos: La Comunidad del Anillo' => 'Primera parte de la épica saga de fantasía de J.R.R. Tolkien.',
            'Introducción al Machine Learning' => 'Conceptos fundamentales y aplicaciones prácticas del aprendizaje automático.',
            'Bases de Datos Relacionales' => 'Fundamentos de diseño y gestión de bases de datos relacionales.',
            'Química Orgánica' => 'Estudio completo de compuestos orgánicos y sus reacciones.',
            'Historia del Arte Universal' => 'Recorrido por las principales corrientes artísticas de la humanidad.',
            'Cálculo Diferencial e Integral' => 'Conceptos y aplicaciones del cálculo diferencial e integral.',
            'Psicología del Desarrollo' => 'Estudio del desarrollo humano desde la infancia hasta la vejez.',
            'Filosofía Contemporánea' => 'Análisis de las principales corrientes filosóficas del siglo XX y XXI.',
            'Álgebra Lineal' => 'Teoría y aplicaciones del álgebra lineal en ciencias e ingeniería.',
            'Biología Molecular' => 'Fundamentos de biología a nivel molecular y celular.',
            'Derecho Procesal Civil' => 'Procedimientos y normativa del derecho procesal civil peruano.',
            'Estadística Aplicada' => 'Métodos estadísticos y su aplicación en ciencias sociales.',
            'Marketing Digital' => 'Estrategias y herramientas del marketing en la era digital.',
        ];

        DB::table('book_details')->insert([
            'book_id' => $bookId,
            'description' => $descriptions[$book['title']] ?? 'Descripción del libro.',
            'edition' => '1ra',
            'file_format' => 'PDF',
            'file_size' => rand(1, 50).' MB',
            'reading_age' => $book['access_level'] === 'institutional' ? '18+' : 'Todas las edades',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
    }

    private function createContributors($bookId, $title)
    {
        $authors = [
            'Cien Años de Soledad' => [['name' => 'Gabriel García Márquez', 'type' => 'author']],
            'El Mundo es Ancho y Ajeno' => [['name' => 'Ciro Alegría', 'type' => 'author']],
            'La Ciudad y los Perros' => [['name' => 'Mario Vargas Llosa', 'type' => 'author']],
            'Historia del Perú Contemporáneo' => [['name' => 'Carlos Contreras', 'type' => 'author'], ['name' => 'Marcos Cueto', 'type' => 'author']],
            'Introducción a la Programación con Python' => [['name' => 'Juan Pérez', 'type' => 'author']],
            'Constitución Política del Perú Comentada' => [['name' => 'Marcial Rubio Correa', 'type' => 'author']],
            'Anatomía Humana Descriptiva' => [['name' => 'Henri Rouvière', 'type' => 'author'], ['name' => 'André Delmas', 'type' => 'author']],
            'Microeconomía Avanzada' => [['name' => 'Hal Varian', 'type' => 'author']],
            'Pedagogía del Oprimido' => [['name' => 'Paulo Freire', 'type' => 'author']],
            'Física Cuántica para Ingenieros' => [['name' => 'David Griffiths', 'type' => 'author']],
            'Don Quijote de la Mancha' => [['name' => 'Miguel de Cervantes', 'type' => 'author']],
            'Rayuela' => [['name' => 'Julio Cortázar', 'type' => 'author']],
            'El Señor de los Anillos: La Comunidad del Anillo' => [['name' => 'J.R.R. Tolkien', 'type' => 'author']],
            'Introducción al Machine Learning' => [['name' => 'Andrew Ng', 'type' => 'author']],
            'Bases de Datos Relacionales' => [['name' => 'Ramez Elmasri', 'type' => 'author'], ['name' => 'Shamkant Navathe', 'type' => 'author']],
            'Química Orgánica' => [['name' => 'John McMurry', 'type' => 'author']],
            'Historia del Arte Universal' => [['name' => 'Ernst Gombrich', 'type' => 'author']],
            'Cálculo Diferencial e Integral' => [['name' => 'James Stewart', 'type' => 'author']],
            'Psicología del Desarrollo' => [['name' => 'Diane Papalia', 'type' => 'author']],
            'Filosofía Contemporánea' => [['name' => 'Bertrand Russell', 'type' => 'author']],
            'Álgebra Lineal' => [['name' => 'Gilbert Strang', 'type' => 'author']],
            'Biología Molecular' => [['name' => 'Bruce Alberts', 'type' => 'author']],
            'Derecho Procesal Civil' => [['name' => 'Juan Monroy Gálvez', 'type' => 'author']],
            'Estadística Aplicada' => [['name' => 'Ronald Walpole', 'type' => 'author']],
            'Marketing Digital' => [['name' => 'Philip Kotler', 'type' => 'author'], ['name' => 'Hermawan Kartajaya', 'type' => 'author']],
        ];

        $contributors = $authors[$title] ?? [['name' => 'Autor Desconocido', 'type' => 'author']];

        foreach ($contributors as $index => $contributor) {
            DB::table('book_contributors')->insert([
                'book_id' => $bookId,
                'contributor_type' => $contributor['type'],
                'full_name' => $contributor['name'],
                'sequence_number' => $index + 1,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
